#!/bin/sh
###############################################################################
# Specify nodes, processors per node and maximum running time
###############################################################################

#PBS -l select=1:ncpus=24:mpiprocs=1
#PBS -l walltime=04:00:00

###############################################################################
# Enter directory and set PATH
###############################################################################

cd $PBS_O_WORKDIR
PATH=$PBS_O_PATH

###############################################################################
# Run OpenMC
###############################################################################

MV2_ENABLE_AFFINITY=0
export MV2_ENABLE_AFFINITY
 
#PBS -k eo
OMP_NUM_THREADS=24
export OMP_NUM_THREADS
python spatial-mesh.py